# Generated by Django 4.2.10 on 2024-03-18 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('nascimento', models.DateField(verbose_name='data de nascimento')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='cpf')),
                ('email', models.EmailField(blank=True, default='Sem email', max_length=120, null=True)),
                ('rede_social', models.EmailField(blank=True, help_text='Informe o link do Instagram, Facebook...', max_length=255, null=True)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='salário')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.cidade')),
            ],
        ),
    ]
