# Generated by Django 4.2.13 on 2024-07-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0002_apartamento_porteiro_remove_pessoa_rede_social_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="visita",
            old_name="visita",
            new_name="visita_de",
        ),
        migrations.AddField(
            model_name="visita",
            name="nome",
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
    ]
