# Generated by Django 4.2.13 on 2024-07-08 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0003_rename_visita_visita_visita_de_visita_nome"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visita",
            name="nome",
        ),
        migrations.RemoveField(
            model_name="visita",
            name="visita_de",
        ),
        migrations.AddField(
            model_name="visita",
            name="pessoa_visita",
            field=models.ForeignKey(
                default=12,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visitas_feitas",
                to="cadastros.pessoa",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="visita",
            name="pessoa_visitada",
            field=models.ForeignKey(
                default=134,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visitas_recebidas",
                to="cadastros.morador",
            ),
            preserve_default=False,
        ),
    ]
