# Generated by Django 4.2.13 on 2024-08-19 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cadastros", "0004_remove_visita_nome_remove_visita_visita_de_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="visita",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pessoa",
            name="email",
            field=models.EmailField(blank=True, max_length=120, null=True),
        ),
    ]
