# Generated by Django 4.2.13 on 2024-09-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_visita_user_alter_pessoa_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
